version: '3'

services:
  db:
    container_name: postgres
    image: postgres:latest
  rails:
    container_name: rails
    build: ./backend
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./backend:/app
    ports:
      - '3000:3000'
    depends_on:
      - db
