version: '2.1'

services:
  rails_app:
    stdin_open: true
    build: .
    environment:
      - DB_HOST_NAME=mysql
    volumes:
      - .:/app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - "3306:3306"
volumes:
  bundle:
    driver: local
